### ISSUE TITLE
Menus should have rounded corners to fit suru-style

### ISSUE THREAD

**Issue by ghost** [ubuntu/gtk-communitheme#183]
Please add "design"-label.

Menus should have rounded corners to fit the suru-style. An example can be found in the pop-theme.
![menus](https://user-images.githubusercontent.com/36449926/36436975-07ef0d36-1666-11e8-9ea9-667523f7ac03.png)

**Comment by madsrh** [comment]
Well spotted @NusiNusi  +1 from me!

**Comment by NusiNusi** [comment]
is it possible to make the highlight with round corners too? i think i remember a mockup from you with round highlights @madsrh

**Comment by Feichtmeier** [comment]
![screenshot from 2018-03-24 10-47-20](https://user-images.githubusercontent.com/15329494/37862652-e3d1c444-2f50-11e8-9d35-65705d8a7c5c.png)
No matter what I try the border always bleeds out of of the background. Tried several google solutions like

-moz-background-clip: padding; 
-webkit-background-clip: padding-box;
background-clip: padding-box;

Nothing removes the border bleed :( 

Thats' what I did

menu,
.menu,
.context-menu {
  margin: 4px;
  box-shadow: 0 2px 5px transparentize(black, 0.75);
  background-color: $menu_color;
  color: $text_color;
  border: 1px solid $borders_color; 
  border-radius: 10px; // <----------------------------------- That

**Comment by madsrh** [comment]
The United theme has rounded corners as well, so @godlyranchdressing

**Comment by Feichtmeier** [comment]
Ah cool I'll look into that and see how he does it :dagger: I guess he is faster anyways but let's see :)

**Comment by NusiNusi** [comment]
@Feichtmeier The Canta-theme has round menus too: https://www.omgubuntu.co.uk/2018/03/canta-gtk-theme-rounded-corners?utm_source=slideshow

**Comment by NusiNusi** [comment]
Another thing is: the color of checkboxes should be inverted, like in the rest of the theme (box should be green and checkmark should be white). not sure if i should open a new issue for this or we can talk about this here.
![bildschirmfoto vom 2018-03-25 22-06-55](https://user-images.githubusercontent.com/36449926/37935254-1b83410e-3151-11e8-8638-0a8f8a594ca6.png)

**Comment by madsrh** [comment]
@NusiNusi I don't want to derail the conversation to checkboxes 😄 but perhaps we should rather remove the inverted checkboxes? This looks better IMO:

![check](https://user-images.githubusercontent.com/3986894/37962455-73539fae-31bb-11e8-8441-3e404630bcbf.gif)

@Feichtmeier Did you look into the [United code](https://github.com/godlyranchdressing/United-GNOME/tree/master/src/gnome-shell/sass/common-partials) (or Pop OS) for?

**Comment by Feichtmeier** [comment]
@madsrh yeah, tried many things - the background still bleeds out of the radius. I look into that later today again. Unitedgnome is a little bit different organized but I stay optimistic :)

**Comment by NusiNusi** [comment]
@madsrh that it is what i meant. remove the inverted version OR invert the inverted. green box and white checkmark everywhere but in different sizes. or some different design. it should just be everywhere the same, on menus too.

**Comment by NusiNusi** [comment]
@Feichtmeier i still have some work to do but maybe i can later look for other themes with rounded menus. Maybe their code is easier to "implement" in communitheme.

**Comment by clobrano** [comment]
About radio and check buttons, didn't we already agreed on this design?
https://github.com/CanonicalLtd/desktop-design/tree/master/Check%20boxes%20and%20radio%20buttons

**Comment by madsrh** [comment]
> About radio and check buttons, didn't we already agreed on this design?

😃 Yes, we did, but there isn't a design in these specs for a selected checkbox in list view (on orange background). None of [these ](https://github.com/CanonicalLtd/desktop-design/blob/master/Check%20boxes%20and%20radio%20buttons/checkboxes.png)are inverted.

You don't [like this one](https://user-images.githubusercontent.com/3986894/37962455-73539fae-31bb-11e8-8441-3e404630bcbf.gif)? If you think it blends too much into the orange we can add a very light green border outside the checkbox, but I think this one is fine (my mockup uses a darker green for the selected checkboxes)

**Comment by clobrano** [comment]
> smiley Yes, we did @clobrano, but there isn't a design in these specs for a selected checkbox in list view (on orange background).

I agree on a change for orange background :+1: 
What about keeping the same green? Not enough noticeable?

**Comment by madsrh** [comment]
IMO no but almost - give it a try. I think the color in the mockup looks slightly more distinct. As@nussinussi said should we create a separate issue or you on it @clobrano

**Comment by clobrano** [comment]
> IMO no but almost - give it a try. I think the color in the mockup looks slightly more distinct. 

ok, I'll try

> As@NussiNussi said should we create a separate issue or are you on it @clobrano ?

yes please :)

**Comment by NusiNusi** [comment]
@Feichtmeier I could find the lines in the code of the canta-theme for the rounded menus. Should i post it here? Would that help you? Its a bit long...

**Comment by Feichtmeier** [comment]
@NusiNusi sure why not :)

**Comment by NusiNusi** [comment]
This is from the canta-theme:

``/*********
 * Menus *
 *********/
menubar,
.menubar {
  -GtkWidget-window-dragging: true;
  padding: 0;
  // box-shadow: inset 0 -1px $border_color;
  background-color: $titlebar_bg_color;

  > menuitem {
    transition: $shorter_transition;
    min-height: 20px;
    padding: 4px 8px;
    color: $titlebar_secondary_fg_color;

    &:hover { // Seems like it :hover even with keyboard focus
//      transition: none;
//      background-color: $titlebar_divider_color;
      color: $titlebar_fg_color;
      box-shadow: inset 0 -3px $primary_color;
    }

    &:disabled { color: $titlebar_disabled_secondary_fg_color; }

    label:disabled { color: inherit; } // to inherit the above color
  }
}

.csd.popup { background-color: transparent; }

menu,
.menu,
.context-menu {
  margin: 4px 0; // See https://bugzilla.gnome.org/show_bug.cgi?id=591258
  padding: 4px 0;
  box-shadow: inset 0 1px $highlight_color;
  background-color: rgba($menu_bg_color, 0.96);
  border: 1px solid $border_color; // adds borders in a non composited env

  .csd & {
    border: none; // axes borders in a composited env
    border-radius: $buttons_radius;
  }

  menuitem {
    transition: background-color $shorter_duration $deceleration_curve;
    min-height: 20px;
    min-width: 40px;
    padding: 4px 8px;
    font: initial;
    text-shadow: none;

    &:hover {
      transition: none;
      background-color: $primary_color;
      color: $inverse_fg_color;

      accelerator { color: $inverse_secondary_fg_color; }
    }

    &:disabled { color: $disabled_fg_color; }

    // submenu indicators
    arrow {
      min-height: 16px;
      min-width: 16px;

      &:dir(ltr) {
        -gtk-icon-source: -gtk-icontheme('pan-end-symbolic');
        margin-left: 8px;
      }

      &:dir(rtl) {
        -gtk-icon-source:-gtk-icontheme('pan-end-symbolic-rtl');
        margin-right: 8px;
      }
    }

    // avoids labels color being overridden, see
    // https://bugzilla.gnome.org/show_bug.cgi?id=767058
    label { &:dir(rtl), &:dir(ltr) { color: inherit; }}
  }

  // overflow arrows
  > arrow {
    min-height: 16px;
    min-width: 16px;
    padding: 4px;
    background-color: $base_color;
    color: $secondary_fg_color;

    &.top {
      margin-top: -4px;
      border-bottom: 1px solid $border_color;
      border-radius: $buttons_radius $buttons_radius 0 0;
      -gtk-icon-source: -gtk-icontheme('pan-up-symbolic');
    }

    &.bottom {
      margin-bottom: -4px * 3;
      border-top: 1px solid $border_color;
      border-radius: 0 0 $buttons_radius $buttons_radius;
      -gtk-icon-source: -gtk-icontheme('pan-down-symbolic');
    }

    &:hover {
      background-image: image($divider_color);
      color: $fg_color;
    }

    &:disabled {
      border-color: transparent;
      background-color: transparent;
      color: transparent;
      // color: $disabled_secondary_fg_color;
    }
  }

  separator { margin: 4px 0; }
}

menuitem {
  accelerator { color: $secondary_fg_color; }
}

// FIXME: THIS IS A REALLY UGLY WORKAROUND!
// Electron/Atom render all translucent colors in opaque colors.
// It's a very critical issue for this theme and should be fixed by upstream...
.popup:not(.csd) menu {
  menuitem {
    color: $opaque_fg_color;

    &:hover { background-color: $opaque_divider_color; }

    &:disabled { color: $opaque_disabled_fg_color; } // separator/border also use this color.
  }

  // FIXME: not working this
  accelerator { color: $opaque_secondary_fg_color; }
}

**Comment by clobrano** [comment]
Rounded borders in contextual menu fixed by #301 
Keep this open for checkboxes and radio

**Comment by Feichtmeier** [comment]
@nana-4 
I just noticed that the border bleed is still present in firefox 
![screenshot from 2018-04-02 17-14-03](https://user-images.githubusercontent.com/15329494/38201645-45fae9f8-3699-11e8-9713-89e5648b279b.png)

**Comment by godlyranchdressing** [comment]
@Feichtmeier I tried, but I don't know if it's possible.

**Comment by Feichtmeier** [comment]
@godlyranchdressing what about these old properties?

-moz-border-radius-topright: 
-webkit-border-top-right-radius:
-moz-border-radius-bottomright: 
-webkit-border-bottom-right-radius: 
-moz-border-radius-bottomleft:
-webkit-border-bottom-left-radius:

**Comment by clobrano** [comment]
Those are only for web browsers

**Comment by clobrano** [comment]
Fixed by many changes :) closing this and opening a new ticket specifically for Firefox (just to track any decision about it)
