### ISSUE TITLE
Context Menus have wrong border-radius

### ISSUE THREAD

**Issue by pojntfx** [ubuntu/gtk-communitheme#316]
In Nautilus, context menus have a wrong border-radius sometimes:

![screenshot from 2018-04-06 01-03-36](https://user-images.githubusercontent.com/28832235/38396070-5cc3c494-3936-11e8-89bc-1db3081b6108.png)

This also applies to the desktop (look closely at the top left and right of the hovered item):

![screenshot from 2018-04-06 01-04-12](https://user-images.githubusercontent.com/28832235/38396096-80795764-3936-11e8-9f2c-9a248281506a.png)

**Comment by clobrano** [comment]
Not sure if I understood, what do you mean by "wrong" radius

**Comment by pojntfx** [comment]
Bottom image as example:

How it should be:
Non-rounded | Non-rounded
Rounded | Rounded

How it is:
Rounded | Rounded
Rounded | Rounded

In detail:
![screenshot of problem](https://ibb.co/iZSaEx)

**Comment by clobrano** [comment]
I understood now, you meant on hover :+1:

**Comment by CDrummond** [comment]
I guess its related to this, or eve caused by the fix for this? But the 1st item in a combobox's popup menu has the same issue - in that the bottom corners are now rounded.

**Comment by clobrano** [comment]
uhm, could you give me an example to where to look at?

**Comment by CDrummond** [comment]
From gtk-3-widget-factory:

![combo](https://user-images.githubusercontent.com/1141694/38498683-1c60e7e6-3bfd-11e8-9640-d032d7456231.png)

**Comment by pojntfx** [comment]
Nautilus issue seems to be fixed, but now there is another problem in `gnome-terminal` (same as in Nautilus before):

![screenshot from 2018-04-09 15-15-13](https://user-images.githubusercontent.com/28832235/38499791-f1b1b262-3c08-11e8-832e-a87b69314b51.png)

I can also confirm @CDrummond's problem in GTK3 widget factory.

**Comment by CDrummond** [comment]
Should this issue not be re-opened? Or shall I create a new issue for the combobox menu problem?

**Comment by Feichtmeier** [comment]
Seems fixed here, pulled today:

![screenshot from 2018-04-15 23-50-30](https://user-images.githubusercontent.com/15329494/38783814-e94cc46e-4107-11e8-887e-bd2e384ec214.png)

**Comment by CDrummond** [comment]
Yes, I know its fixed for context menus. That's **not** what I said. It's broken for the **first** item in **combobox** menus. And, its still broken. Hence asking whether this should be re-opened, or create a new report.

**Comment by Feichtmeier** [comment]
Fixed with https://github.com/ubuntu/gtk-communitheme/pull/340 by the awesome @godlyranchdressing
