### ISSUE TITLE
Modal dialogs have no shadow

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/gtk-communitheme#600]
As can be seen in the following screenshot, the confirmation dialog has no shadow. Which is OK when the message window (its parent) is larger then it, but looks odd otherwise. Perhaps a slight shadow should always be added to these?

![evolution](https://user-images.githubusercontent.com/1141694/42153922-5ed1f0a4-7ddc-11e8-90f6-93f403113256.png)

**Comment by Feichtmeier** [comment]
Nice catch! That would be awkward to ship!

**Comment by CDrummond** [comment]
@madsrh Not sure why you have tagged this `gtk2-theme`, evolution is a gtk3 app.

**Comment by Feichtmeier** [comment]
@CDrummond maybe because it looks very old school? ;D Just a little joke! :dancer:

**Comment by clobrano** [comment]
Not sure we can do much with css here. I did fix another type of **modaldialog** today (so no wasted time :D)

![image](https://user-images.githubusercontent.com/2883614/42418725-49c4eeae-82a6-11e8-8de6-39cf6ea50a92.png)

![image](https://user-images.githubusercontent.com/2883614/42418688-c04ba122-82a5-11e8-9ade-d8e82bb39607.png)


but this one seems different. It's root is called **dialog** only, but it's not THE window, but a child of it, so I cannot get control of the whole window decoration

![image](https://user-images.githubusercontent.com/2883614/42418722-3ad5533e-82a6-11e8-957c-75b137425a90.png)

as you can see I can add a border, but the box-shadow does nothing

![image](https://user-images.githubusercontent.com/2883614/42418677-935484a4-82a5-11e8-85c9-4139b8c0dc98.png)

**Comment by CDrummond** [comment]
Yeah, adding a border here might be the best that can be done. Ambiance has no shadow, or border, and Adwaita has no shadow.

**Comment by clobrano** [comment]
I haven't thought about adding a border, I'll check the effect later

**Comment by Paz-it** [comment]
Hi @clobrano @CDrummond 
See this tread here https://github.com/horst3180/arc-theme/issues/8 
May you'll get an idea how to go about it.

**Comment by clobrano** [comment]
Unfortunately what suggested in the thread mentioned by  @Paz-it is what I did for modal-dialog, but did not work for dialog. However, I just observed the following:

This is "normal" dialog window
![image](https://user-images.githubusercontent.com/2883614/42566266-520d56e8-8506-11e8-97ef-056ea4057c75.png)

This is the same window after a Xorg restart (ALT-r)
![image](https://user-images.githubusercontent.com/2883614/42566297-6c04b442-8506-11e8-94b1-6f53095f4771.png)

it looks like something is wrong here

**Comment by Feichtmeier** [comment]
@clobrano is there any relation to the "big" gtk dialogue change that was made several months ago? Or is it a gtk2 dialogue?

**Comment by clobrano** [comment]
@Paz-it thank you, but that is for message dialog, which as said is fixable. message-dialog and dialog are different things

**Comment by Paz-it** [comment]
@Feichtmeier  gave me an idea, can it be Gnome-shell related dialog? :thinking: ...

**Comment by Feichtmeier** [comment]
@Paz-it no. I think it's also fixed with that PR :D

**Comment by clobrano** [comment]
The dialog comes from the window, so no shell. I am going to ask upstream if there is something they can do about this gtk-dialog

**Comment by CDrummond** [comment]
How can this be closed? Dialog as shown in original message still does not have a shadow.

To recreate:

1. Start evolution - press 'cancel' at the welcome dialog (
2. Start to compose a new message - text in subject or body
3. Close editor dialog - warning should now be shown

**Comment by clobrano** [comment]
@CDrummond this has been closed automatically when PR has been merged, but if you go through the messages I said I will ask upstream why restarting the shell draws the shadows below the window.
My understanding is that if it was a communitheme issue, redraw should not change anything

**Comment by CDrummond** [comment]
@clobrano fair point! Sorry, I should have read the PR more closely :-(  And I can confirm restarting the shell does produce a shadow.
